--- 
services: 
  redis: 
    networks:
      - redis-network
    command: 
      - redis-server
      - "--appendonly"
      - "yes"
    image: redis
    ports: 
      - "6379:6379"

  upload: 
    networks:
      - api-network
      - redis-network
    build: .
    command: npm start
    environment:
      - NODE_ENV=development
    depends_on: 
      - redis
    ports: 
      - "3000:3000"
    restart: always
    volumes:
      - ./data/media/incoming/.:/data/media/incoming
      - ./data/media/images/.:/data/media/images
      - ./data/media/audio/.:/data/media/audio
      - /var/www/api/node_modules

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
      - htpasswd:/etc/nginx/htpasswd
    depends_on:
      - nodejs
      - choo
    networks:
      - app-network
      - api-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email auggod@resonate.is --agree-tos --no-eff-email --force-renewal -d upload.resonate.ninja

networks:
  api-network:
    driver: bridge
  app-network:
    driver: bridge
  redis-network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
  htpasswd:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/htpasswd/"
      o: bind
  web-root:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/public/"
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/dhparam/"
      o: bind

version: "3.7"
